### ISSUE TITLE
Find Compatible objects with each api and list name and id with api to search for

### ISSUE THREAD

**Issue by SKYRIMpro1** [SKYRIMpro1/MealTime#7]

**Comment by SKYRIMpro1** [comment]
8 objects

**Comment by aidanangelowashere** [comment]
Chicken alfredo:

FDCID - 2114180
"idMeal":"52796"
Name - Chicken Alfredo Primavera

Beef Wellington:

FDCID -1099326
"idMeal":"52803"
Name - Beef Wellington

Beef Stroganoff:

FDCID = 2059778
"idMeal":"52834"
Name - Beef stroganoff

Egg Drop Soup :

FDCID = 1100336
"idMeal":"52955"
Name - Egg Drop Soup

Margherita Pizza:

FDCID: 482200
"idMeal":"53014"
Name - Pizza Express Margherita


Tomato Soup:

FDCID: 1626547
"idMeal":"52841"
Name - Creamy Tomato Soup

French Onion Soup:

FDCID: 461428
"idMeal":"52903"
Name - French Onion Soup

General Tso's Chicken: 

FDCID: 1648551
"idMeal":"52951"
Name- General Tso's Chicken
