### ISSUE TITLE
Elevator pitch

### ISSUE THREAD

**Issue by SKYRIMpro1** [SKYRIMpro1/MealTime#9]

**Comment by Keithm0258** [comment]
Hi there we are group four and I noticed you were having a hard time choosing what you wanna eat for dinner.
Well just so happens our team of developers have the solution for you. We created a website called MealTime that lets you select a healthy meal when you run out of ideas. After selecting your meal it will show you the ingredients and nutritional facts. We’ve had a ton of positive feedback from families telling us how much our website helped when their kids or spouse were being picky or they just had no clue of what to eat! What do you say wanna give it a try?
